backend:
  name: github
  repo: ba-arch-b/-shatina-nails
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    fields:
      - {label: "名稱", name: "title", widget: "string"}
      - {label: "圖片", name: "image", widget: "image"}
      - {label: "介紹", name: "description", widget: "text"}